:- discontiguous poem/3.

poem(sayori, notitle, ['get', 'out', 'of', 'my', 'head', 'get', 'out', 'of', 'my', 'head', 'get', 'out', 'of', 'my', 'head', 'get', 'out', 'of', 'my', 'head', 'get', 'out', 'of', 'my', 'head', 'get', 'out', 'of', 'my', 'head', 'get', 'out', 'of', 'my', 'head', 'get', 'out', 'of', 'my', 'head', 'get', 'out', 'of', 'my', 'head', 'get', 'out', 'of', 'my', 'head', 'get', 'out', 'of', 'my', 'head', 'get', 'out', 'of', 'my', 'head', 'get', 'out', 'of', 'my', 'head', 'get', 'out', 'of', 'my', 'head', 'get', 'out', 'of', 'my', 'head', 'get', 'out', 'of', 'my', 'head', 'get', 'out', 'of', 'my', 'head', 'get', 'out', 'of', 'my', 'head', 'get', 'out', 'of', 'my', 'head', 'get', 'out', 'of', 'my', 'head', 'get', 'out', 'of', 'my', 'head', 'get', 'out', 'of', 'my', 'head', 'get', 'out', 'of', 'my', 'head', 'get', 'out', 'of', 'my', 'head', 'get', 'out', 'of', 'my', 'head', 'get', 'out', 'of', 'my', 'head', 'get', 'out', 'of', 'my', 'head', 'get', 'out', 'of', 'my', 'head', 'get', 'out', 'of', 'my', 'head', 'get', 'out', 'of', 'my', 'head', 'get', 'out', 'of', 'my', 'head', 'get', 'out', 'of', 'my', 'head', 'get', 'out', 'of', 'my', 'head', 'get', 'out', 'of', 'my', 'head', 'get', 'out', 'of', 'my', 'head', 'get', 'out', 'of', 'my', 'head', 'get', 'out', 'of', 'my', 'head', 'get', 'out', 'of', 'my', 'head', 'get', 'out', 'of', 'my', 'head', 'get', 'out', 'of', 'get', 'out', 'of', 'my', 'head', 'get', 'out', 'of', 'my', 'head', 'before', 'i', 'do', 'what', 'i', 'know', 'is', 'best', 'for', 'you', 'get', 'out', 'of', 'my', 'head', 'before', 'i', 'listen', 'to', 'everything', 'she', 'said', 'to', 'me', 'get', 'out', 'of', 'my', 'head', 'before', 'i', 'show', 'you', 'how', 'much', 'i', 'love', 'you', 'get', 'out', 'of', 'my', 'head', 'before', 'i', 'finish', 'writing', 'this', 'poem', 'but', 'a', 'poem', 'is', 'never', 'actually', 'finished', 'it', 'just', 'stops', 'moving']).
poem(natsuki, amy_likes_spiders, ['you', 'know', 'what', 'i', 'heard', 'about', 'amy', 'amy', 'likes', 'spiders', 'icky', 'wriggly', 'hairy', 'ugly', 'spiders', 'that', 's', 'why', 'i', 'm', 'not', 'friends', 'with', 'her', 'amy', 'has', 'a', 'cute', 'singing', 'voice', 'i', 'heard', 'her', 'singing', 'my', 'favorite', 'love', 'song', 'every', 'time', 'she', 'sang', 'the', 'chorus', 'my', 'heart', 'would', 'pound', 'to', 'the', 'rhythm', 'of', 'the', 'words', 'but', 'she', 'likes', 'spiders', 'that', 's', 'why', 'i', 'm', 'not', 'friends', 'with', 'her', 'one', 'time', 'i', 'hurt', 'my', 'leg', 'really', 'bad', 'amy', 'helped', 'me', 'up', 'and', 'took', 'me', 'to', 'the', 'nurse', 'i', 'tried', 'not', 'to', 'let', 'her', 'touch', 'me', 'she', 'likes', 'spiders', 'so', 'her', 'hands', 'are', 'probably', 'gross', 'that', 's', 'why', 'i', 'm', 'not', 'friends', 'with', 'her', 'amy', 'has', 'a', 'lot', 'of', 'friends', 'i', 'always', 'see', 'her', 'talking', 'to', 'people', 'she', 'probably', 'talks', 'about', 'spiders', 'what', 'if', 'her', 'friends', 'start', 'to', 'like', 'spiders', 'too', 'that', 's', 'why', 'i', 'm', 'not', 'friends', 'with', 'her', 'it', 'doesn', 't', 'matter', 'if', 'she', 'has', 'other', 'hobbies', 'it', 'doesn', 't', 'matter', 'if', 'she', 'keeps', 'it', 'private', 'it', 'doesn', 't', 'matter', 'if', 'it', 'doesn', 't', 'hurt', 'anyone', 'it', 's', 'gross', 'she', 's', 'gross', 'the', 'world', 'is', 'better', 'off', 'without', 'spider', 'lovers', 'and', 'i', 'm', 'gonna', 'tell', 'everyone']).
poem(monika, the_lady_who_knows_everything, ['an', 'old', 'tale', 'tells', 'of', 'a', 'lady', 'who', 'wanders', 'earth', 'the', 'lady', 'who', 'knows', 'everything', 'a', 'beautiful', 'lady', 'who', 'has', 'found', 'every', 'answer', 'all', 'meaning', 'all', 'purpose', 'and', 'all', 'that', 'was', 'ever', 'sought', 'and', 'here', 'i', 'am', 'a', 'feather', 'lost', 'adrift', 'the', 'sky', 'victim', 'of', 'the', 'currents', 'of', 'the', 'wind', 'day', 'after', 'day', 'i', 'search', 'i', 'search', 'with', 'little', 'hope', 'knowing', 'legends', 'don', 't', 'exist', 'but', 'when', 'all', 'else', 'has', 'failed', 'me', 'when', 'all', 'others', 'have', 'turned', 'away', 'the', 'legend', 'is', 'all', 'that', 'remains', 'the', 'last', 'dim', 'star', 'glimmering', 'in', 'the', 'twilit', 'sky', 'until', 'one', 'day', 'the', 'wind', 'ceases', 'to', 'blow', 'i', 'fall', 'and', 'i', 'fall', 'and', 'fall', 'and', 'fall', 'even', 'more', 'gentle', 'as', 'a', 'feather', 'a', 'dry', 'quill', 'expressionless', 'but', 'a', 'hand', 'catches', 'me', 'between', 'the', 'thumb', 'and', 'forefinger', 'the', 'hand', 'of', 'a', 'beautiful', 'lady', 'i', 'look', 'at', 'her', 'eyes', 'and', 'find', 'no', 'end', 'to', 'her', 'gaze', 'the', 'lady', 'who', 'knows', 'everything', 'knows', 'what', 'i', 'am', 'thinking', 'before', 'i', 'can', 'speak', 'she', 'responds', 'in', 'a', 'hollow', 'voice', 'i', 'have', 'found', 'every', 'answer', 'all', 'of', 'which', 'amount', 'to', 'nothing', 'there', 'is', 'no', 'meaning', 'there', 'is', 'no', 'purpose', 'and', 'we', 'seek', 'only', 'the', 'impossible', 'i', 'am', 'not', 'your', 'legend', 'your', 'legend', 'does', 'not', 'exist', 'and', 'with', 'a', 'breath', 'she', 'blows', 'me', 'back', 'afloat', 'and', 'i', 'pick', 'up', 'a', 'gust', 'of', 'wind']).
poem(natsuki, eagles_can_fly, ['monkeys', 'can', 'climb', 'crickets', 'can', 'leap', 'horses', 'can', 'race', 'owls', 'can', 'seek', 'cheetahs', 'can', 'run', 'eagles', 'can', 'fly', 'people', 'can', 'try', 'but', 'that', 's', 'about', 'it']).
poem(monika, hole_in_wall, ['it', 'couldn', 't', 'have', 'been', 'me', 'see', 'the', 'direction', 'the', 'spackle', 'protrudes', 'a', 'noisy', 'neighbor', 'an', 'angry', 'boyfriend', 'i', 'll', 'never', 'know', 'i', 'wasn', 't', 'home', 'i', 'peer', 'inside', 'for', 'a', 'clue', 'no', 'i', 'can', 't', 'see', 'i', 'reel', 'blind', 'like', 'a', 'film', 'left', 'out', 'in', 'the', 'sun', 'but', 'it', 's', 'too', 'late', 'my', 'retinas', 'already', 'scorched', 'with', 'a', 'permanent', 'copy', 'of', 'the', 'meaningless', 'image', 'it', 's', 'just', 'a', 'little', 'hole', 'it', 'wasn', 't', 'too', 'bright', 'it', 'was', 'too', 'deep', 'stretching', 'forever', 'into', 'everything', 'a', 'hole', 'of', 'infinite', 'choices', 'i', 'realize', 'now', 'that', 'i', 'wasn', 't', 'looking', 'in', 'i', 'was', 'looking', 'out', 'and', 'he', 'on', 'the', 'other', 'side', 'was', 'looking', 'in']).
poem(robson, i_dont_know, ['watching', 'about', 'feelings', 'feeling', 'like', 'how', 'it', 'would', 'feel', 'compensation', 'is', 'the', 'word', 'that', 'repeats', 'endlessly', 'but', 'i', 'think', 'nothing', 'it', 's', 'like', 'a', 'havoc', 'is', 'happening', 'deep', 'inside', 'my', 'fragile', 'mind', 'it', 'thinks', 'so', 'highly', 'of', 'it', 'on', 'top', 'of', 'anything', 'diverging', 'of', 'others', 'selves', 'how', 'meaningful', 'are', 'words', 'that', 'are', 'heard', 'without', 'listening', 'how', 'good', 'am', 'i', 'to', 'see', 'the', 'world', 'around', 'in', 'the', 'end', 'it', 'all', 'results', 'in', 'nothing', 'nothing', 'is', 'categorized', 'though', 'it', 'grows', 'like', 'dark', 'matter', 'expanding', 'twisting', 'space', 'invading', 'turning', 'creeping', 'disappearing', 'and', 'so', 'hollow', 'be', 'i']).
poem(yuri, ghost_under_the_light, ['the', 'tendrils', 'of', 'my', 'hair', 'illuminate', 'beneath', 'the', 'amber', 'glow', 'bathing', 'it', 'must', 'be', 'this', 'one', 'the', 'last', 'remaining', 'streetlight', 'to', 'have', 'withstood', 'the', 'test', 'of', 'time', 'the', 'last', 'yet', 'to', 'be', 'replaced', 'by', 'the', 'sickening', 'blue', 'green', 'hue', 'of', 'the', 'future', 'i', 'bathe', 'calm', 'breathing', 'air', 'of', 'the', 'present', 'but', 'living', 'in', 'the', 'past', 'the', 'light', 'flickers', 'i', 'flicker', 'back']).
poem(natsuki, because_you, ['tomorrow', 'will', 'be', 'brighter', 'with', 'me', 'around', 'but', 'when', 'today', 'is', 'dim', 'i', 'can', 'only', 'look', 'down', 'my', 'looking', 'is', 'a', 'little', 'more', 'forward', 'because', 'you', 'look', 'at', 'me', 'when', 'i', 'want', 'to', 'say', 'something', 'i', 'say', 'it', 'with', 'a', 'shout', 'but', 'my', 'truest', 'feelings', 'can', 'never', 'come', 'out', 'my', 'words', 'are', 'a', 'little', 'less', 'empty', 'because', 'you', 'listen', 'to', 'me', 'when', 'something', 'is', 'above', 'me', 'i', 'reach', 'for', 'the', 'stars', 'but', 'when', 'i', 'feel', 'small', 'i', 'don', 't', 'get', 'very', 'far', 'my', 'standing', 'is', 'a', 'little', 'bit', 'taller', 'because', 'you', 'sit', 'with', 'me', 'i', 'believe', 'in', 'myself', 'with', 'all', 'of', 'my', 'heart', 'but', 'what', 'do', 'i', 'do', 'when', 'it', 's', 'torn', 'all', 'apart', 'my', 'faith', 'is', 'a', 'little', 'bit', 'stronger', 'because', 'you', 'trusted', 'me', 'my', 'pen', 'always', 'puts', 'my', 'feelings', 'to', 'the', 'test', 'i', 'm', 'not', 'a', 'good', 'writer', 'but', 'my', 'best', 'is', 'my', 'best', 'my', 'poems', 'are', 'a', 'little', 'bit', 'dearer', 'because', 'you', 'think', 'of', 'me', 'because', 'you', 'because', 'you', 'because', 'you']).
poem(sayori, bottles, ['i', 'pop', 'off', 'my', 'scalp', 'like', 'the', 'lid', 'of', 'a', 'cookie', 'jar', 'it', 's', 'the', 'secret', 'place', 'where', 'i', 'keep', 'all', 'my', 'dreams', 'little', 'balls', 'of', 'sunshine', 'all', 'rubbing', 'together', 'like', 'a', 'bundle', 'of', 'kittens', 'i', 'reach', 'inside', 'with', 'my', 'thumb', 'and', 'forefinger', 'and', 'pluck', 'one', 'out', 'it', 's', 'warm', 'and', 'tingly', 'but', 'there', 's', 'no', 'time', 'to', 'waste', 'i', 'put', 'it', 'in', 'a', 'bottle', 'to', 'keep', 'it', 'safe', 'and', 'i', 'put', 'the', 'bottle', 'on', 'the', 'shelf', 'with', 'all', 'of', 'the', 'other', 'bottles', 'happy', 'thoughts', 'happy', 'thoughts', 'happy', 'thoughts', 'in', 'bottles', 'all', 'in', 'a', 'row', 'my', 'collection', 'makes', 'me', 'lots', 'of', 'friends', 'each', 'bottle', 'a', 'starlight', 'to', 'make', 'amends', 'sometimes', 'my', 'friend', 'feels', 'a', 'certain', 'way', 'down', 'comes', 'a', 'bottle', 'to', 'save', 'the', 'day', 'night', 'after', 'night', 'more', 'dreams', 'friend', 'after', 'friend', 'more', 'bottles', 'deeper', 'and', 'deeper', 'my', 'fingers', 'go', 'like', 'exploring', 'a', 'dark', 'cave', 'discovering', 'the', 'secrets', 'hiding', 'in', 'the', 'nooks', 'and', 'crannies', 'digging', 'and', 'digging', 'scraping', 'and', 'scraping', 'i', 'blow', 'dust', 'off', 'my', 'bottle', 'caps', 'it', 'doesn', 't', 'feel', 'like', 'time', 'elapsed', 'my', 'empty', 'shelf', 'could', 'use', 'some', 'more', 'my', 'friends', 'look', 'through', 'my', 'locked', 'front', 'door', 'finally', 'all', 'done', 'i', 'open', 'up', 'and', 'in', 'come', 'my', 'friends', 'in', 'they', 'come', 'in', 'such', 'a', 'hurry', 'do', 'they', 'want', 'my', 'bottles', 'that', 'much', 'i', 'frantically', 'pull', 'them', 'from', 'the', 'shelf', 'one', 'after', 'the', 'other', 'holding', 'them', 'out', 'to', 'each', 'and', 'every', 'friend', 'each', 'and', 'every', 'bottle', 'but', 'every', 'time', 'i', 'let', 'one', 'go', 'it', 'shatters', 'against', 'the', 'tile', 'between', 'my', 'feet', 'happy', 'thoughts', 'happy', 'thoughts', 'happy', 'thoughts', 'in', 'shards', 'all', 'over', 'the', 'floor', 'they', 'were', 'supposed', 'to', 'be', 'for', 'my', 'friends', 'my', 'friends', 'who', 'aren', 't', 'smiling', 'they', 're', 'all', 'shouting', 'pleading', 'something', 'but', 'all', 'i', 'hear', 'is', 'echo', 'echo', 'echo', 'echo', 'echo', 'inside', 'my', 'head']).
poem(yuri, the_raccoon, ['it', 'happened', 'in', 'the', 'dead', 'of', 'night', 'while', 'i', 'was', 'slicing', 'bread', 'for', 'a', 'guilty', 'snack', 'my', 'attention', 'was', 'caught', 'by', 'the', 'scuttering', 'of', 'a', 'raccoon', 'outside', 'my', 'window', 'that', 'was', 'i', 'believe', 'the', 'first', 'time', 'i', 'noticed', 'my', 'strange', 'tendencies', 'as', 'an', 'unordinary', 'human', 'i', 'gave', 'the', 'raccoon', 'a', 'piece', 'of', 'bread', 'my', 'subconscious', 'well', 'aware', 'of', 'the', 'consequences', 'well', 'aware', 'that', 'a', 'raccoon', 'that', 'is', 'fed', 'will', 'always', 'come', 'back', 'for', 'more', 'the', 'enticing', 'beauty', 'of', 'my', 'cutting', 'knife', 'was', 'the', 'symptom', 'the', 'bread', 'my', 'hungry', 'curiosity', 'the', 'raccoon', 'an', 'urge', 'the', 'moon', 'increments', 'its', 'phase', 'and', 'reflects', 'that', 'much', 'more', 'light', 'off', 'of', 'my', 'cutting', 'knife', 'the', 'very', 'same', 'light', 'that', 'glistens', 'in', 'the', 'eyes', 'of', 'my', 'raccoon', 'friend', 'i', 'slice', 'the', 'bread', 'fresh', 'and', 'soft', 'the', 'raccoon', 'becomes', 'excited', 'or', 'perhaps', 'i', 'm', 'merely', 'projecting', 'my', 'emotions', 'onto', 'the', 'newly', 'satisfied', 'animal', 'the', 'raccoon', 'has', 'taken', 'to', 'following', 'me', 'you', 'could', 'say', 'that', 'we', 've', 'gotten', 'quite', 'used', 'to', 'each', 'other', 'the', 'raccoon', 'becomes', 'hungry', 'more', 'and', 'more', 'frequently', 'so', 'my', 'bread', 'is', 'always', 'handy', 'every', 'time', 'i', 'brandish', 'my', 'cutting', 'knife', 'the', 'raccoon', 'shows', 'me', 'its', 'excitement', 'a', 'rush', 'of', 'blood', 'classic', 'pavlovian', 'conditioning', 'i', 'slice', 'the', 'bread', 'and', 'i', 'feed', 'myself', 'again']).
poem(sayori, dear_sunshine, ['the', 'way', 'you', 'glow', 'through', 'my', 'blinds', 'in', 'the', 'morning', 'it', 'makes', 'me', 'feel', 'like', 'you', 'missed', 'me', 'kissing', 'my', 'forehead', 'to', 'help', 'me', 'out', 'of', 'bed', 'making', 'me', 'rub', 'the', 'sleepy', 'from', 'my', 'eyes', 'are', 'you', 'asking', 'me', 'to', 'come', 'out', 'and', 'play', 'are', 'you', 'trusting', 'me', 'to', 'wish', 'away', 'a', 'rainy', 'day', 'i', 'look', 'above', 'the', 'sky', 'is', 'blue', 'it', 's', 'a', 'secret', 'but', 'i', 'trust', 'you', 'too', 'if', 'it', 'wasn', 't', 'for', 'you', 'i', 'could', 'sleep', 'forever', 'but', 'i', 'm', 'not', 'mad', 'i', 'want', 'breakfast']).
poem(yuri, ghost_under_the_light_pt_2, ['the', 'tendrils', 'of', 'my', 'hair', 'illuminate', 'beneath', 'the', 'amber', 'glow', 'bathing', 'in', 'the', 'distance', 'a', 'blue', 'green', 'light', 'flickers', 'a', 'lone', 'figure', 'crosses', 'its', 'path', 'a', 'silhouette', 'obstructing', 'the', 'eerie', 'glow', 'my', 'heart', 'pounds', 'the', 'silhouette', 'grows', 'closer', 'closer', 'i', 'open', 'my', 'umbrella', 'casting', 'a', 'shadow', 'to', 'shield', 'me', 'from', 'visibility', 'but', 'i', 'am', 'too', 'late', 'he', 'steps', 'into', 'the', 'streetlight', 'i', 'gasp', 'and', 'drop', 'my', 'umbrella', 'the', 'light', 'flickers', 'my', 'heart', 'pounds', 'he', 'raises', 'his', 'arm', 'time', 'stops', 'the', 'only', 'indication', 'of', 'movement', 'is', 'the', 'amber', 'light', 'flickering', 'against', 'his', 'outstretched', 'arm', 'the', 'flickering', 'light', 'is', 'in', 'rhythm', 'with', 'the', 'pounding', 'of', 'my', 'heart', 'teasing', 'me', 'for', 'succumbing', 'to', 'this', 'forbidden', 'emotion', 'have', 'you', 'ever', 'heard', 'of', 'a', 'ghost', 'feeling', 'warmth', 'before', 'giving', 'up', 'on', 'understanding', 'i', 'laugh', 'understanding', 'is', 'overrated', 'i', 'touch', 'his', 'hand', 'the', 'flickering', 'stops', 'ghosts', 'are', 'blue', 'green', 'my', 'heart', 'is', 'amber']).
poem(monika, save_me, ['the', 'colors', 'they', 'won', 't', 'stop', 'bright', 'beautiful', 'colors', 'flashing', 'expanding', 'piercing', 'red', 'green', 'blue', 'an', 'endless', 'cacophony', 'of', 'meaningless', 'noise', 'the', 'noise', 'it', 'won', 't', 'stop', 'violent', 'grating', 'waveforms', 'squeaking', 'screeching', 'piercing', 'sine', 'cosine', 'tangent', 'like', 'playing', 'a', 'chalkboard', 'on', 'a', 'turntable', 'like', 'playing', 'a', 'vinyl', 'on', 'a', 'pizza', 'crust', 'an', 'endless', 'poem', 'of', 'meaningless', 'load', 'me']).

p1(Word) :- poem(_, _, Words), member(Word, Words).
p2(PreviousWord, Word) :- poem(_, _, Words), append(_, [PreviousWord, Word|_], Words).
p3(PreviousWord, Word, NextWord) :- poem(_, _, Words), append(_, [PreviousWord, Word, NextWord|_], Words).
pc1(Word, Author) :- poem(Author, _, Words), member(Word, Words).
pc2(PreviousWord, Word, Author) :- poem(Author, _, Words), append(_, [PreviousWord, Word|_], Words).
pc3(PreviousWord, Word, NextWord, Author) :- poem(Author, _, Words), append(_, [PreviousWord, Word, NextWord|_], Words).
next_words(Word, L) :- findall(Next, p3(_, Word, Next), L).
count_occ(_, [], 0).
count_occ(X, [X|T], Count) :- count_occ(X, T, Count1), Count is Count1 + 1.
count_occ(X, [Y|T], Count) :- X \= Y, count_occ(X, T, Count).
remove_all(_, [], []).
remove_all(X, [X|T], R) :- remove_all(X, T, R).
remove_all(X, [Y|T], [Y|R]) :- X \= Y, remove_all(X, T, R).
count_list([], []).
count_list([H|T], [H-Count|R]) :- count_occ(H, [H|T], Count), remove_all(H, T, NewT), count_list(NewT, R).
next_word_counts(Word, Counts) :- next_words(Word, NextWords), count_list(NextWords, Counts).
next_word_counts_author(Author, Word, Counts) :- findall(Next, pc3(_, Word, Next, Author), NextWords), count_list(NextWords, Counts).
most_frequent_pair([], _, _) :- fail.
most_frequent_pair([W-C], W, C).
most_frequent_pair([W1-C1, _-C2 | T], BW, BC) :- C1 >= C2, most_frequent_pair([W1-C1 | T], BW, BC).
most_frequent_pair([_-C1, W2-C2 | T], BW, BC) :- C1 < C2, most_frequent_pair([W2-C2 | T], BW, BC).
most_frequent_next(Word, NextWord, Count) :- next_word_counts(Word, Counts), most_frequent_pair(Counts, NextWord, Count).
most_frequent_next_author(Author, Word, NextWord, Count) :- next_word_counts_author(Author, Word, Counts), most_frequent_pair(Counts, NextWord, Count).
most_frequent_word(Word, Count) :- findall(Word, p1(Word), Words), count_list(Words, Counts), most_frequent_pair(Counts, Word, Count).
most_frequent_word_author(Author, Word, Count) :- findall(Word, pc1(Word, Author), Words), count_list(Words, Counts), most_frequent_pair(Counts, Word, Count).
new_poem(Start, Length, Poem) :- poem(_, _, Words), append(_, [Start|_], Words), generate_poem(Start, 1, Length, Poem).
generate_poem(_, Count, MaxCount, []) :- Count > MaxCount.
generate_poem(Current, Count, MaxCount, [Current|Rest]) :- Count =< MaxCount, most_frequent_next(Current, Next, _), NewCount is Count + 1, generate_poem(Next, NewCount, MaxCount, Rest).
new_author_poem(Author, Start, Length, Poem) :- poem(Author, _, Words), append(_, [Start|_], Words), generate_author_poem(Author, Start, 1, Length, Poem).
generate_author_poem(_, _, Count, MaxCount, []) :- Count > MaxCount.
generate_author_poem(Author, Current, Count, MaxCount, [Current|Rest]) :- Count =< MaxCount, most_frequent_next_author(Author, Current, Next, _), NewCount is Count + 1, generate_author_poem(Author, Next, NewCount, MaxCount, Rest).
